services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cafecompao93
      MYSQL_DATABASE: db_products
      MYSQL_USER: products
      MYSQL_PASSWORD: cafecompao93
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
